services:
  - type: web
    name: mental-health-chatbot
    env: python3.9
    buildCommand: pip install -r requirements.txt
    startCommand: chainlit run app.py
    envVars:
      - key: PORT
        value: 10000
